### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by varHarrie** [varHarrie/apate-desktop#1]
- [x] **特性** 国际化
- [x] **特性** 多个编辑面板
- [ ] **特性** 编辑项目信息
- [ ] **特性** 删除项目
- [ ] **特性** 删除接口
- [ ] **特性** mock函数
- [ ] **特性** 显示接口状态（正常、请求中、错误）
- [ ] **特性** 显示项目状态（未激活、激活、错误）
- [ ] **特性** 服务器处理请求
- [ ] **特性** 服务器状态

- [x] **改进** Tab双击固定
- [x] **改进** 统一Icon，使用svg
- [ ] **改进** Input回车确定
- [ ] **改进** 创建接口，解析描述，与method区分
- [ ] **改进** 响应式布局
- [ ] **改进** 程序Logo和图标
- [ ] **改进** 空白位置展示
- [ ] **改进** 完善ScrollArea
- [ ] **改进** 完善TabBar

- [ ] **Bug** 编辑时，组件下移，产生滚动条
- [ ] **Bug** 鼠标中键点击链接创建新窗口
